name: 2023_kohyass_LoRA_dogA_Cmix_B2_Iter500
manual_seed: 0
mixed_precision: fp16

# dataset and data loader settings
datasets:
  train:
    name: LoraDataset
    concept_list: datasets/data_cfgs/MixofShow/single-concept/objects/real/dogA.json
    use_caption: true
    instance_transform:
      - { type: Resize, size: 512}
      - { type: RandomCrop, size: 512 }
      - { type: ToTensor }
      - { type: Normalize, mean: [ 0.5 ], std: [ 0.5 ] }
      - { type: ShuffleCaption, keep_token_num: 1 }
      - { type: EnhanceText, enhance_type: object }
    replace_mapping:
      <TOK>: <dogA>
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100

  val_vis:
    name: PromptDataset
    prompts: datasets/validation_prompts/single-concept/objects/test_dog.txt
    num_samples_per_prompt: 8
    latent_size: [ 4,64,64 ]
    replace_mapping:
      <TOK>: <dogA>
    batch_size_per_gpu: 4

models:
  pretrained_path: experiments/pretrained_models/chilloutmix
  enable_edlora: false  # true means ED-LoRA, false means vallina LoRA
  finetune_cfg:
    text_embedding:
      enable_tuning: true
      lr: !!float 1e-3
    text_encoder:
      enable_tuning: true
      lora_cfg:
        rank: 128
        alpha: 1.0
        where: CLIPAttention
      lr: !!float 1e-5
    unet:
      enable_tuning: true
      lora_cfg:
        rank: 128
        alpha: 1.0
        where: Attention
      lr: !!float 1e-4
  new_concept_token: <dogA>
  initializer_token: dog
  noise_offset: 0.01
  gradient_checkpoint: false
  enable_xformers: true

# path
path:
  pretrain_network: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 0.0 # no use since we define different component lr in model
    weight_decay: 0.01
    betas: [ 0.9, 0.999 ] # align with taming

  # dropkv
  unet_kv_drop_rate: 0

  scheduler: linear
  total_iter: 500 # 5 epoch
  warmup_iter: 0  # no warm up

# validation settings
val:
  val_freq: 10000
  compose_visualize: true
  vis_embedding: true
  sample:
    num_inference_steps: 50
    guidance_scale: 7.5

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 10000
